WEB/WebApplication_Uitleendienst/ViewComponents/AuthenticationViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.Models.ViewModels;

namespace WebApplication_Uitleendienst.ViewComponents {
    public class AuthenticationViewComponent : ViewComponent {

        public AuthenticationViewComponent(){

        }

        public async Task<IViewComponentResult> InvokeAsync(){
            var model = new HomeViewModel(HttpContext);          
            return View("_LoginPartial", model);
        }
    }

}

WEB/WebApplication_Uitleendienst/ViewComponents/CartViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.Models;
using WebApplication_Uitleendienst.Models.ViewModels.Cart;

namespace WebApplication_Uitleendienst.ViewComponents {
    public class CartViewComponent : ViewComponent {
        public async Task<IViewComponentResult> InvokeAsync(){ 
            var model = new CartViewModel();
            var cart = HttpContext.Request.Cookies["Cart"];
            if(cart != null){
                model.Cart = JsonConvert.DeserializeObject<List<CartItem>>(cart);
            }
            return View("_CartCounter", model);
        }
    }
}

WEB/WebApplication_Uitleendienst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication_Uitleendienst</title>
    <link rel="stylesheet" href="~/bundles/css/assets.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link asp-subresource-integrity href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@200;300;400&display=swap" rel="stylesheet">

</head>
<body>
    <section data-bs-version="5.1" class="menu menu3 cid-sOXcLCVPp1" once="menu" id="menu3-1j">

        <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
            <div class="container">
                <div class="navbar-brand">

                    <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7" href="#!"><img src="~/images/logo/logo.png" /></a></span>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <div class="hamburger">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                        <li class="nav-item">
                            <a class="nav-link link text-black" href="/">
                                Home
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link text-black" href="/catalogue/catalogue">
                                Catalogue
                            </a>
                        </li>
                    </ul>
                    <div class="icons-menu">
                        <a class="iconfont-wrapper" href="#!" target="_blank">
                            <span class="p-2 mbr-iconfont socicon-facebook socicon"></span>
                        </a>
                        <a class="iconfont-wrapper" href="#!" target="_blank">
                            <span class="p-2 mbr-iconfont socicon-twitter socicon"></span>
                        </a>
                        <a class="iconfont-wrapper" href="#!" target="_blank">
                            <span class="p-2 mbr-iconfont socicon-instagram socicon"></span>
                        </a>

                    </div>

                    @await Component.InvokeAsync("Authentication")
                    <ul class="navbar-nav d-flex align-items-center">
                        <li class="nav-item">
                            <a href="/cart/index" class="text-dark">
                                <i class="fas fa-shopping-cart"></i>
                                <span>@await Component.InvokeAsync("Cart")</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </section>
    <div class="container">
        <main role="main" class="pb-3">
            @if (ViewBag.Breadcrumbs != null) {
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-white justify-content-center justify-content-md-start justify-content-lg-start justify-content-xl-start">
                        @foreach (var breadcrumb in ViewBag.Breadcrumbs as List<Breadcrumb>) {
                            if (breadcrumb.Active) {
                                <li class="breadcrumb-item active"><a asp-action="@breadcrumb.Action" asp-controller="@breadcrumb.Controller">@breadcrumb.Text</a></li>
                            } else {
                                <li class="breadcrumb-item" aria-current="page">@breadcrumb.Text</li>
                            }
                        }
                    </ol>
                </nav>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebApplication_Uitleendienst - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script asp-subresource-integrity src="https://kit.fontawesome.com/31f5f08539.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/bundles/js/assets.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>