WEB/WebApplication_Uitleendienst/Models/Core/Magazijn.cs
using Newtonsoft.Json;

namespace WebApplication_Uitleendienst
{
	public class Magazijn
	{
		private string id;
		private string naam;
		private string adres;
		private string telefoon;
		private string email;
		private string opmerking;

		public Magazijn()
		{
		}

		public Magazijn(string naam, string adres, string telefoon, string email, string opmerking)
		{
			this.naam = naam;
			this.adres = adres;
			this.telefoon = telefoon;
			this.email = email;
			this.opmerking = opmerking;
		}
		[JsonProperty("id")]
		public virtual string Id
		{
			get
			{
				return id;
			}
			set
			{
				this.id = value;
			}
		}

		[JsonProperty("naam")]
		public virtual string Naam
		{
			get
			{
				return naam;
			}
			set
			{
				this.naam = value;
			}
		}
		[JsonProperty("adres")]
		public virtual string Adres
		{
			get
			{
				return adres;
			}
			set
			{
				this.adres = value;
			}
		}

		[JsonProperty("telefoon")]
		public virtual string Telefoon
		{
			get
			{
				return telefoon;
			}
			set
			{
				this.telefoon = value;
			}
		}

		[JsonProperty("email")]
		public virtual string Email
		{
			get
			{
				return email;
			}
			set
			{
				this.email = value;
			}
		}
		[JsonProperty("opmerking")]
		public virtual string Opmerking
		{
			get
			{
				return opmerking;
			}
			set
			{
				this.opmerking = value;
			}
		}
	}

}

WEB/WebApplication_Uitleendienst/Models/ViewModels/Magazijns/MagazijnViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication_Uitleendienst.Models.ViewModels.Magazijns {
    public class MagazijnViewModel : BaseViewModel {
        public IEnumerable<Magazijn> Magazijnen { get; set; }
        public Magazijn Magazijn { get; set; }
        public List<Uitlening> Uitleningen { get; set; }
        public List<UitleenbaarItem> Products { get; set; }
        public UitleenbaarItem Product { get; set; }
        public BeschikbaarItem BeschikbaarItem { get; set; }
    }
}

WEB/WebApplication_Uitleendienst/Areas/Admin/Controllers/MagazijnController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.Models.ViewModels.Magazijns;
using WebApplication_Uitleendienst.Services.Interfaces;

namespace WebApplication_Uitleendienst.Areas.Admin.Controllers {
    [Area("Admin")]
    public class MagazijnController : BaseAdminController {
        private readonly IBaseService<Magazijn> _magazijnService;

        public MagazijnController(IBaseService<Magazijn> magazijnService) {
            _magazijnService = magazijnService;
        }
        public IActionResult Index(MagazijnViewModel model) {
            if (model == null)
                model = new MagazijnViewModel();
            model.Magazijnen = _magazijnService.GetAll(token: UserInfo.Token);
            return View(model);
        }

        public IActionResult Create() {
            return View();
        }

        public IActionResult Detail(string Id) {
            var magazijn = _magazijnService.Get(propertyValue: Id, token: UserInfo.Token);
            return View(magazijn);
        }

        public IActionResult Edit(string Id) {
            var magazijn = _magazijnService.Get(propertyValue: Id, token: UserInfo.Token);
            return View(magazijn);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(Magazijn mag) {
            var entity = await _magazijnService.Save(mag, token: UserInfo.Token);
            return RedirectToAction("index");
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(Magazijn mag) {
            var entity = await _magazijnService.Update(mag, customEntity: mag.Id, token: UserInfo.Token);
            return RedirectToAction("index");
        }

        public async Task<IActionResult> Delete(string id) {
            var model = new MagazijnViewModel();
            try {
                _magazijnService.Delete(id, token: UserInfo.Token);
                model.Message = "Item is succesvol verwijderd.";
                model.Level = Models.ViewModels.InfoLevel.success;

            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = Models.ViewModels.InfoLevel.danger;
            }
            return RedirectToAction("Index", model);
        }

    }
}

WEB/WebApplication_Uitleendienst/Areas/MagazijnContact/Controllers/MagazijnController.cs
using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.AuthorizeAttributes;
using WebApplication_Uitleendienst.Models.ViewModels;
using WebApplication_Uitleendienst.Models.ViewModels.Magazijns;
using WebApplication_Uitleendienst.Services.Interfaces;
using WebApplication_Uitleendienst.Utilities;

namespace WebApplication_Uitleendienst.Areas.MagazijnContact.Controllers {
    [Area("MagazijnContact")]
    public class MagazijnController : BaseController {
        private readonly IBaseService<ContactMagazijn> _contactMagazijnService;
        private readonly IBaseService<Persoon> _persoonService;
        private readonly IBaseService<Magazijn> _magazijnService;
        private readonly IBaseService<Uitlening> _uitleningsService;
        private readonly IBaseService<BeschikbaarItem> _beschikbaarItemService;
        private readonly IBaseService<UitleenbaarItem> _uitleenbaarItemService;
        private readonly IBaseService<Categorie> _categorieService;

        private IConverter _converter;

        public MagazijnController(IBaseService<Categorie> categorieService, IConverter converter, IBaseService<BeschikbaarItem> beschikbaarItemService, IBaseService<UitleenbaarItem> uitleenbaarItemService, IBaseService<Uitlening> UitleningService, IBaseService<ContactMagazijn> contactMagService, IBaseService<Persoon> persoonService, IBaseService<Magazijn> magazijnService) {
            _persoonService = persoonService;
            _contactMagazijnService = contactMagService;
            _magazijnService = magazijnService;
            _uitleningsService = UitleningService;
            _uitleenbaarItemService = uitleenbaarItemService;
            _beschikbaarItemService = beschikbaarItemService;
            _converter = converter;
            _categorieService = categorieService;
        }
        public IActionResult Index(MagazijnViewModel model = null) {
            if (model == null)
                model = new MagazijnViewModel();
            try {
                // retrieve current contactmag info
                var persoon = _persoonService.GetAll(propertyName: "username", propertyValue: UserInfo.Username, token: UserInfo.Token)?.FirstOrDefault();
                var contactmag = new ContactMagazijn();
                if (persoon != null) {
                    contactmag = _contactMagazijnService.GetAll(propertyName: "persoonId", propertyValue: persoon.Id, token: UserInfo.Token)?.FirstOrDefault();
                    if (contactmag != null) {
                        model.Magazijn = _magazijnService.Get(propertyValue: contactmag.magazijnId, token: UserInfo.Token);
                        model.Uitleningen =
                            _uitleningsService.GetAll(token: UserInfo.Token)?
                            .Where(u => u.MagazijnId == contactmag.magazijnId)
                            .ToList();
                    } else {
                        throw new Exception("Gebruiker is geen bestaande magazijnverantwoordelijke");
                    }

                    var beschikbareItems = _beschikbaarItemService.GetAll(token: UserInfo.Token)
                        .Where(s => s.MagazijnId == contactmag.magazijnId)
                        .Select(b => b.UitleenbaarItemId);

                    var uitleenbareItems = _uitleenbaarItemService.GetAll(token: UserInfo.Token);

                    model.Products = uitleenbareItems
                        .Where(s => beschikbareItems.Any(p => p.Equals(s.Id)))
                        .ToList();

                } else {
                    model.Message = "Geen geldige contactinformatie gevonden voor huidige gebruiker";
                    model.Level = InfoLevel.danger;
                }
            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = InfoLevel.danger;
            }

            return View(model);
        }
        public IActionResult CreateUitleenbaarItem() {
            var model = new MagazijnViewModel();
            try {
                var categories = _categorieService.GetAll(token: UserInfo.Token);
                if (categories != null) {
                    var item = new UitleenbaarItem {
                        Categories = categories
                    };
                    return View(item);
                } else {
                    model.Message = $"Er zijn geen categorieën gevonden, gelieve deze eerst aan te maken alvorens een product te creëeren. <p><a href='{ Url.Action("Create", "Category", new { area = "Admin" }) }'>Aanmaken</a></p>";
                    model.Level = Models.ViewModels.InfoLevel.warning;
                    return RedirectToAction("Index", model);
                }
            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = InfoLevel.danger;
                return RedirectToAction("index", model);
            }
        }

        public IActionResult CreateBeschikbaarItem(string id) {
            var model = new MagazijnViewModel();
            try {
                model.Product = _uitleenbaarItemService.Get(propertyValue: id, token: UserInfo.Token);
                // retrieve current contactmag info
                var persoon = _persoonService.GetAll(propertyName: "username", propertyValue: UserInfo.Username, token: UserInfo.Token)?.FirstOrDefault();
                var contactmag = new ContactMagazijn();
                if (persoon != null) {
                    contactmag = _contactMagazijnService.GetAll(propertyName: "persoonId", propertyValue: persoon.Id, token: UserInfo.Token)?.FirstOrDefault();
                    if (contactmag != null)
                        model.Magazijn = _magazijnService.Get(propertyValue: contactmag.magazijnId, token: UserInfo.Token);
                }
            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = InfoLevel.danger;
                return RedirectToAction("index", model);
            }
            return View(model);
        }

        public IActionResult Detail(string Id) {
            var model = new MagazijnViewModel();
            try {
                var prod = _uitleenbaarItemService.Get(propertyValue: Id, token: UserInfo.Token);
                return View(prod);
            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = InfoLevel.danger;
                return RedirectToAction("index", model);
            }
        }

        public IActionResult Edit(string Id) {
            var model = new MagazijnViewModel();
            try {
                var prod = _uitleenbaarItemService.Get(propertyValue: Id, token: UserInfo.Token);
                if (prod != null)
                    prod.Categories = _categorieService.GetAll(token: UserInfo.Token);
                return View(prod);
            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = InfoLevel.danger;
                return RedirectToAction("index", model);
            }
        }


        [HttpPost]
        public async Task<IActionResult> EditPost(UitleenbaarItem prod) {
            var model = new MagazijnViewModel();
            try {
                var item = await _uitleenbaarItemService.Update(prod, customEntity: prod.Id, token: UserInfo.Token);
                if (item == null) {
                    model.Message = "Item kon niet worden geupdated.";
                    model.Level = Models.ViewModels.InfoLevel.danger;
                } else {
                    model.Message = "Item is succesvol geupdated.";
                    model.Level = Models.ViewModels.InfoLevel.success;
                }
            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = InfoLevel.danger;
                return RedirectToAction("index", model);
            }
            return RedirectToAction("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(UitleenbaarItem prod) {
            var model = new MagazijnViewModel();
            try {
                var entity = await _uitleenbaarItemService.Save(prod, token: UserInfo.Token);
                if (entity == null) {
                    model.Message = "Item kon niet worden opgeslagen.";
                    model.Level = Models.ViewModels.InfoLevel.danger;
                } else {
                    model.Message = "Item is succesvol opgeslagen.";
                    model.Level = Models.ViewModels.InfoLevel.success;
                }
            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = InfoLevel.danger;
                return RedirectToAction("index", model);
            }
            return RedirectToAction("Index", model);
        }


        public async Task<IActionResult> Delete(string id) {
            var model = new MagazijnViewModel();
            try {
                _uitleenbaarItemService.Delete(id, token: UserInfo.Token);
                model.Message = "Item is succesvol verwijderd.";
                model.Level = Models.ViewModels.InfoLevel.success;

            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = Models.ViewModels.InfoLevel.danger;
            }
            return RedirectToAction("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePostBeschikbaar(MagazijnViewModel model) {
            try {
                var entity = await _beschikbaarItemService.Save(model.BeschikbaarItem, token: UserInfo.Token);
                if (entity == null) {
                    model.Message = "Beschikbaarheid kon niet worden opgeslagen.";

WEB/WebApplication_Uitleendienst/ViewComponents/MessageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.Models.ViewModels;

namespace WebApplication_Uitleendienst.ViewComponents {
    public class MessageViewComponent: ViewComponent {
        public async Task<IViewComponentResult> InvokeAsync(BaseViewModel baseViewModel){      
            return View("_Message", baseViewModel);
        }
    }
}

WEB/WebApplication_Uitleendienst/Areas/Admin/Views/Magazijn/Create.cshtml
@model WebApplication_Uitleendienst.Magazijn

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Magazijn</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePost" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adres" class="control-label"></label>
                <input asp-for="Adres" class="form-control" />
                <span asp-validation-for="Adres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefoon" class="control-label"></label>
                <input asp-for="Telefoon" class="form-control" />
                <span asp-validation-for="Telefoon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opmerking" class="control-label"></label>
                <input asp-for="Opmerking" class="form-control" />
                <span asp-validation-for="Opmerking" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WEB/WebApplication_Uitleendienst/Areas/Admin/Views/Magazijn/Detail.cshtml
@model Magazijn

@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detail</h1>

<div>
    <h4>Categorie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {Id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

WEB/WebApplication_Uitleendienst/Areas/Admin/Views/Magazijn/Edit.cshtml
@model WebApplication_Uitleendienst.Magazijn

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Categorie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPost" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" name="Id" value="@Model.Id" />
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefoon" class="control-label"></label>
                <input asp-for="Telefoon" class="form-control" />
                <span asp-validation-for="Telefoon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adres" class="control-label"></label>
                <input asp-for="Adres" class="form-control" />
                <span asp-validation-for="Adres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opmerking" class="control-label"></label>
                <input asp-for="Opmerking" class="form-control" />
                <span asp-validation-for="Opmerking" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WEB/WebApplication_Uitleendienst/Areas/Admin/Views/Magazijn/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model WebApplication_Uitleendienst.Models.ViewModels.Magazijns.MagazijnViewModel


@await Component.InvokeAsync("Message", @Model)

<div class="category-wrapper">
    <ul class="navbar-nav d-flex align-items-center float-left">
        <li>
            <a class="nav-link btn btn-dark px-2 py-1" asp-area="Admin" asp-controller="Magazijn" asp-action="Create" title="Magazijn">
                <i class="fa-solid fa-plus"></i>
                <i class="fa-solid fa-sitemap"></i>
            </a>
        </li>
    </ul>

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Naam</th>
                <th scope="col">Detail</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Magazijnen != null) {
                @foreach (var mag in Model.Magazijnen) {
                    <tr>
                        <td>@mag.Naam</td>
                        <td>
                            <a class="nav-link btn btn-light px-2 py-1" asp-area="Admin" asp-controller="Magazijn" asp-action="Detail" asp-route-id="@mag.Id" title="Magazijn">

                                <i class="fa-solid fa-eye"></i>
                            </a>
                        </td>
                        <td class="delete">
                            <a asp-area="Admin" asp-controller="Magazijn" asp-action="Delete" asp-route-id="@mag.Id">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>