WEB/WebApplication_Uitleendienst/Models/ViewModels/Product/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication_Uitleendienst.Models.ViewModels.Product {
    public class ProductViewModel : BaseViewModel {
        public IEnumerable<UitleenbaarItem> Products { get; set; }
        public UitleenbaarItem Product { get; set; }
        public IEnumerable<Magazijn> Magazijnen { get; set; }
        public BeschikbaarItem BeschikbaarItem { get; set; }
    }
}

WEB/WebApplication_Uitleendienst/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.Models.ViewModels.Categories;
using WebApplication_Uitleendienst.Models.ViewModels.Product;
using WebApplication_Uitleendienst.Services.Interfaces;

namespace WebApplication_Uitleendienst.Areas.Admin.Controllers {

    [Area("Admin")]
    public class ProductController : BaseAdminController {
        private readonly IBaseService<Categorie> _categoryService;
        private readonly IBaseService<UitleenbaarItem> _uitleenbaarItemService;
        private readonly IBaseService<BeschikbaarItem> _beschikbaarItemService;
        private readonly IBaseService<Magazijn> _magazijnItemService;
        public ProductController(IBaseService<Categorie> catService, IBaseService<UitleenbaarItem> uitleenbaarItemService, IBaseService<BeschikbaarItem> beschikbaarItemService, IBaseService<Magazijn> magazijnItemService) {
            _categoryService = catService;
            _uitleenbaarItemService = uitleenbaarItemService;
            _beschikbaarItemService = beschikbaarItemService;
            _magazijnItemService = magazijnItemService;
        }
        public IActionResult Index(ProductViewModel model = null) {
            if (model == null)
                model = new ProductViewModel();
            model.Products = _uitleenbaarItemService.GetAll();
            return View(model);
        }

        public IActionResult CreateUitleenbaarItem() {
            var model = new ProductViewModel();
            var categories = _categoryService.GetAll();
            if (categories != null) {
                var item = new UitleenbaarItem {
                    Categories = _categoryService.GetAll()
                };
                return View(item);
            } else {
                model.Message = $"Er zijn geen categorieën gevonden, gelieve deze eerst aan te maken alvorens een product te creëeren. <p><a href='{ Url.Action("Create", "Category", new { area = "Admin" }) }'>Aanmaken</a></p>";
                model.Level = Models.ViewModels.InfoLevel.warning;
                return RedirectToAction("Index", model);
            }


        }

        public IActionResult CreateBeschikbaarItem(string id) {
            var model = new ProductViewModel();
            model.Product = _uitleenbaarItemService.Get(propertyValue: id);
            model.Magazijnen = _magazijnItemService.GetAll(token: UserInfo.Token);
            return View(model);
        }

        public IActionResult Detail(string Id) {
            var prod = _uitleenbaarItemService.Get(propertyValue: Id);
            return View(prod);
        }

        public IActionResult Edit(string Id) {
           var model = new ProductViewModel();
            try {
                var prod = _uitleenbaarItemService.Get(propertyValue: Id, token: UserInfo.Token);
                if (prod != null)
                    prod.Categories = _categoryService.GetAll(token: UserInfo.Token);
                return View(prod);
            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = Models.ViewModels.InfoLevel.danger;
                return RedirectToAction("index", model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(UitleenbaarItem prod) {
            var model = new ProductViewModel();
            var item = await _uitleenbaarItemService.Update(prod, customEntity: prod.Id,  token: UserInfo.Token);
            if (item == null) {
                model.Message = "Item kon niet worden geupdated.";
                model.Level = Models.ViewModels.InfoLevel.danger;
            } else {
                model.Message = "Item is succesvol geupdated.";
                model.Level = Models.ViewModels.InfoLevel.success;
            }
            return RedirectToAction("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(UitleenbaarItem prod) {
            var model = new ProductViewModel();
            var entity = await _uitleenbaarItemService.Save(prod, token: UserInfo.Token);
            if (entity == null) {
                model.Message = "Item kon niet worden opgeslagen.";
                model.Level = Models.ViewModels.InfoLevel.danger;
            } else {
                model.Message = "Item is succesvol opgeslagen.";
                model.Level = Models.ViewModels.InfoLevel.success;
            }
            return RedirectToAction("Index", model);
        }

        public async Task<IActionResult> Delete(string id) {
            var model = new ProductViewModel();
            try {
                _uitleenbaarItemService.Delete(id, token: UserInfo.Token);
                model.Message = "Item is succesvol verwijderd.";
                model.Level = Models.ViewModels.InfoLevel.success;

            } catch (Exception ex) {
                model.Message = ex.Message;
                model.Level = Models.ViewModels.InfoLevel.danger;
            }
            return RedirectToAction("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> CreatePostBeschikbaar(ProductViewModel model) {
            var entity = await _beschikbaarItemService.Save(model.BeschikbaarItem, token: UserInfo.Token);
            if (entity == null) {
                model.Message = "Beschikbaarheid kon niet worden opgeslagen.";
                model.Level = Models.ViewModels.InfoLevel.danger;
            } else {
                model.Message = "Beschikbaarheid is succesvol opgeslagen.";
                model.Level = Models.ViewModels.InfoLevel.success;
            }
            return RedirectToAction("Index", model);
        }
    }
}

WEB/WebApplication_Uitleendienst/ViewComponents/MessageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.Models.ViewModels;

namespace WebApplication_Uitleendienst.ViewComponents {
    public class MessageViewComponent: ViewComponent {
        public async Task<IViewComponentResult> InvokeAsync(BaseViewModel baseViewModel){      
            return View("_Message", baseViewModel);
        }
    }
}

WEB/WebApplication_Uitleendienst/Areas/Admin/Views/Product/CreateBeschikbaarItem.cshtml
@model WebApplication_Uitleendienst.Models.ViewModels.Product.ProductViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>BeschikbaarItem</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePostBeschikbaar" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BeschikbaarItem.UitleenbaarItemId" class="control-label"></label>
                <select asp-for="BeschikbaarItem.UitleenbaarItemId">
                        <option value="@Model.Product.Id">@Model.Product.Naam - @Model.Product.Id</option>
                </select>
                <span asp-validation-for="BeschikbaarItem.UitleenbaarItemId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeschikbaarItem.MagazijnId" class="control-label"></label>
                <select asp-for="BeschikbaarItem.MagazijnId">
                    @foreach (var value in Model.Magazijnen) {
                        <option value="@value.Id">@value.Naam - @value.Id</option>
                    }
                </select>
                <span asp-validation-for="BeschikbaarItem.MagazijnId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeschikbaarItem.AantalTotaal" class="control-label"></label>
                <input asp-for="BeschikbaarItem.AantalTotaal" class="form-control" />
                <span asp-validation-for="BeschikbaarItem.AantalTotaal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeschikbaarItem.AantalBeschikbaar" class="control-label"></label>
                <input asp-for="BeschikbaarItem.AantalBeschikbaar" class="form-control" />
                <span asp-validation-for="BeschikbaarItem.AantalBeschikbaar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BeschikbaarItem.AantalGereserveerd" class="control-label"></label>
                <input asp-for="BeschikbaarItem.AantalGereserveerd" class="form-control" />
                <span asp-validation-for="BeschikbaarItem.AantalGereserveerd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WEB/WebApplication_Uitleendienst/Areas/Admin/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model WebApplication_Uitleendienst.Models.ViewModels.Product.ProductViewModel


@await Component.InvokeAsync("Message", @Model)

<div class="category-wrapper">
    <ul class="navbar-nav d-flex align-items-center float-left">
        <li>
            <a class="nav-link btn btn-dark px-2 py-1" asp-area="Admin" asp-controller="Product" asp-action="CreateUitleenbaarItem" title="Product">
                UitleenbaarItem
                <i class="fa-solid fa-plus"></i>
                <i class="fa-solid fa-sitemap"></i>
            </a>
        </li>
    </ul>

    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Naam</th>
                <th scope="col">Detail</th>
                <th scope="col">Beschikbaarheid</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null) {
                @foreach (var prod in Model.Products) {
                    <tr>
                        <td>@prod.Naam</td>
                        <td>
                            <a class="nav-link btn btn-light px-2 py-1" asp-area="Admin" asp-controller="Product" asp-action="Detail" asp-route-id="@prod.Id" title="Product">

                                <i class="fa-solid fa-eye"></i>
                            </a>
                        </td>
                        <td>
                            <a class="nav-link btn btn-dark px-2 py-1" asp-area="Admin" asp-controller="Product" asp-action="CreateBeschikbaarItem" asp-route-id="@prod.Id" title="Product">
                                Voeg beschikbaarheid toe
                                <i class="fa-solid fa-plus"></i>
                            </a>
                        </td>
                        <td class="delete">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Delete" asp-route-id="@prod.Id">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>