WEB/WebApplication_Uitleendienst/Models/ViewModels/Catalogue/CatalogueDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication_Uitleendienst.Models.ViewModels.Catalogue {
    public class CatalogueDetailViewModel : BaseViewModel {
        public IEnumerable<BeschikbaarItem> BeschikbareItems { get; set; }
        public UitleenbaarItem Product { get; set; }
        public int TotalStock { get; set; }
        public List<Magazijn> Magazijnen { get; set; }
    }
}

WEB/WebApplication_Uitleendienst/Models/ViewModels/Catalogue/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication_Uitleendienst.Models.ViewModels.Catalogue {
    public class CatalogueViewModel : BaseViewModel {
        public List<Categorie> SelectedCategories { get; set; }
        public IEnumerable<UitleenbaarItem> Products { get; set; }
        public IEnumerable<Categorie> Categories { get; set; }
    }
}

WEB/WebApplication_Uitleendienst/Controllers/CatalogueController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.Models;
using WebApplication_Uitleendienst.Models.ViewModels.Catalogue;
using WebApplication_Uitleendienst.Models.ViewModels.Identity;
using WebApplication_Uitleendienst.Services.Interfaces;

namespace WebApplication_Uitleendienst.Controllers {
    public class CatalogueController : BaseController {
        private readonly ILogger<HomeController> _logger;
        private readonly IBaseService<Categorie> _categorieService;
        private readonly IBaseService<BeschikbaarItem> _beschikbaarItemService;
        private readonly IBaseService<UitleenbaarItem> _uitleenbaarItemService;
        private readonly IBaseService<Magazijn> _magazijnService;


        public CatalogueController(IBaseService<Categorie> catService, IBaseService<Magazijn> magazijnService, IBaseService<BeschikbaarItem> beschikbaarItemService, IBaseService<UitleenbaarItem> uitleenbaarItemService) {
            _categorieService = catService;
            _beschikbaarItemService = beschikbaarItemService;
            _uitleenbaarItemService = uitleenbaarItemService;
            _magazijnService = magazijnService;
        }

        public IActionResult Detail(UitleenbaarItem item) {
            var model = new CatalogueDetailViewModel();
            model.Product = item;
            model.Magazijnen = new List<Magazijn>();
            model.BeschikbareItems = _beschikbaarItemService.GetAll("uitleenbaarItemId", item.Id, token: UserInfo.Token);
            if (model.BeschikbareItems != null) {
                model.BeschikbareItems.ToList().ForEach(s => {
                    model.TotalStock += (int)s.AantalTotaal;
                    model.Magazijnen.Add(_magazijnService.Get(propertyValue: s.MagazijnId, token: UserInfo.Token));
                });
            }
            return View(model);
        }
        public IActionResult Catalogue(string categories) {

            var model = new CatalogueViewModel();
            model.SelectedCategories = new List<Categorie>();

            if (!string.IsNullOrEmpty(categories)) {
                var items = new List<UitleenbaarItem>();
                var values = new List<string>();

                // add the items based on the specified range of categories
                var catItems = _uitleenbaarItemService.GetAll("categorieId", categories)?.ToList();
                // add the categories to a list of known selected ones
                model.SelectedCategories.Add(_categorieService.Get(propertyValue: categories, token: UserInfo.Token));

                if (catItems == null) {
                    model.Message = "Geen items teruggevonden voor geselecteerde categorie(s). Je krijgt een overzicht van alle items :";
                    model.Level = Models.ViewModels.InfoLevel.info;
                    model.Products = _uitleenbaarItemService.GetAll();
                } else
                    model.Products = catItems;
            } else
                model.Products = _uitleenbaarItemService.GetAll();

            model.Categories = _categorieService.GetAll();
            return View(model);
        }

        public string AddToCart(string productId, string magazijnId, string amount) {
            if (!User.Identity.IsAuthenticated)
                return "not_authenticated";
            try {
                var cart = new List<CartItem>();
                var cartItem = new CartItem {
                    Amount = amount,
                    ProductId = productId,
                    MagazijnId = magazijnId,
                    UserId = new UserInfoPageModel(HttpContext).Username
                };
                var currentCart = HttpContext.Request.Cookies["Cart"];

                if (!string.IsNullOrEmpty(currentCart)) {
                    // when there is info in current cart
                    // use that cartobject as base
                    cart = JsonConvert.DeserializeObject<List<CartItem>>(currentCart);

                }

                // check for any existing occurences
                // if so, add the old amount to the new amount, and remove the occurence from list
                var existingCartItem = cart.Where(s => s.ProductId == cartItem.ProductId && s.MagazijnId == cartItem.MagazijnId).FirstOrDefault();
                if (existingCartItem != null) {
                    cartItem.Amount = (int.Parse(cartItem.Amount) + int.Parse(existingCartItem.Amount)).ToString();
                    cart.Remove(existingCartItem);
                }
                cart.Add(cartItem);

                HttpContext.Response.Cookies.Append("Cart", JsonConvert.SerializeObject(cart), new CookieOptions { HttpOnly = true, SameSite = SameSiteMode.Lax });

                return "success";
            } catch (Exception ex) {
                return ex.Message;
            }

        }
    }
}

WEB/WebApplication_Uitleendienst/ViewComponents/CatalogueViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication_Uitleendienst.ViewComponents {
    public class CatalogueViewComponent : ViewComponent {
        public async Task<IViewComponentResult> InvokeAsync(UitleenbaarItem uitleenbaarItem){      
            return View("_ProductCard", uitleenbaarItem);
        }
    }
}

WEB/WebApplication_Uitleendienst/ViewComponents/MessageViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_Uitleendienst.Models.ViewModels;

namespace WebApplication_Uitleendienst.ViewComponents {
    public class MessageViewComponent: ViewComponent {
        public async Task<IViewComponentResult> InvokeAsync(BaseViewModel baseViewModel){      
            return View("_Message", baseViewModel);
        }
    }
}

WEB/WebApplication_Uitleendienst/Views/Catalogue/Catalogue.cshtml
@model WebApplication_Uitleendienst.Models.ViewModels.Catalogue.CatalogueViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Component.InvokeAsync("Message", @Model)


<div class="container catalogue-wrapper">
    <div class="row catalogue">
        <div class="col-12 col-md-2 filter">
            <!-- Filters -->
            <h2>FILTER</h2>
            <hr />
            <h6>Category</h6>
            <form method="GET" id="formFilters">
                @if (Model.Categories != null) {
                    @foreach (var cat in Model.Categories) {
                        <p>
                            <input @(Model.SelectedCategories.Any(c => c.Id == cat.Id) ? "checked=checked" : "")  type="checkbox" value="@cat.Id" name="categorie" />
                            @cat.Naam
                        </p>
                    }
                }
            </form>
        </div>
        <div class="col-12 col-md-10 products">
            <!-- Catalogue -->
            <div class="row">
                @if (Model.Products != null) {
                    @foreach (var product in Model.Products) {
                        @await Component.InvokeAsync("Catalogue", new { uitleenbaarItem = product });
                    }
                } else {
                    <h6>Er zijn geen producten gevonden.</h6>
                }
            </div>

        </div>
    </div>

</div>

WEB/WebApplication_Uitleendienst/Views/Catalogue/Detail.cshtml
@model WebApplication_Uitleendienst.Models.ViewModels.Catalogue.CatalogueDetailViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var count = 0;
}
<div class="container">

    @await Component.InvokeAsync("Message", @Model)

    @if (Model.Product != null) {<div class="wrapper row detail">
            <input type="hidden" value="@Model.Product.Id" class="product-id" />
            <div class="hidden info-text alert alert-warning">
                <label type="text"></label>
            </div>
            <div class="preview col-md-6">

                <div class="preview-pic tab-content">
                    <div class="tab-pane active" id="pic-1"><img src="~/images/default.png" /></div>
                    <div class="tab-pane" id="pic-2"><img src="~/images/default.png" /></div>
                    <div class="tab-pane" id="pic-3"><img src="~/images/default.png" /></div>
                    <div class="tab-pane" id="pic-4"><img src="~/images/default.png" /></div>
                    <div class="tab-pane" id="pic-5"><img src="~/images/default.png" /></div>
                </div>
                <ul class="preview-thumbnail nav nav-tabs">
                    <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="~/images/default.png" /></a></li>
                    <li><a data-target="#pic-2" data-toggle="tab"><img src="~/images/default.png" /></a></li>
                    <li><a data-target="#pic-3" data-toggle="tab"><img src="~/images/default.png" /></a></li>
                    <li><a data-target="#pic-4" data-toggle="tab"><img src="~/images/default.png" /></a></li>
                    <li><a data-target="#pic-5" data-toggle="tab"><img src="~/images/default.png" /></a></li>
                </ul>

            </div>
            <div class="details col-md-6">
                <h3 class="product-title">@Model.Product.Naam</h3>
                <div class="stock">
                    @if (Model.BeschikbareItems != null) {
                        <h6><span class="font-weight-bold">Totale stock: </span> @Model.TotalStock</h6>
                        <h6 class="font-weight-bold">Kies een magazijn: </h6>
                        @foreach (var magazijn in Model.Magazijnen) {
                            @if (magazijn != null) {
                                <label class="w-100">
                                    <input type="radio" @(count == 0 ? "checked='checked'" : "") name="magazijn" value="@magazijn.Id" />
                                    @magazijn.Naam : @(Model.BeschikbareItems.Where(s => s.MagazijnId == magazijn.Id).FirstOrDefault().AantalBeschikbaar > 0 ? Html.Raw("<span class='beschikbaar'>Beschikbaar</span>") : Html.Raw("<span class='niet-beschikbaar'Niet beschikaar</span>"))
                                </label>
                                count++;
                            }
                        }
                    } else {
                        <h6><span class="font-weight-bold">Dit item is momenteel niet op stock.</span></h6>
                    }
                    <div class="amount">
                        <h6 class="font-weight-bold">Aantal: </h6>
                        <select class="form-control" name="select-amount">
                            <option selected>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>
                </div>
                <p class="product-description">Suspendisse quos? Tempus cras iure temporibus? Eu laudantium cubilia sem sem! Repudiandae et! Massa senectus enim minim sociosqu delectus posuere.</p>
                <h4 class="price">Prijs: <span>€@Model.Product.Prijs</span></h4>
                <div class="action">
                    <a href="#!" @(Model.BeschikbareItems == null ? "disabled" : "") class="add-to-cart m-0 btn btn-dark @(Model.BeschikbareItems == null ? "disabled" : "")" onclick="AddToCart($(this), '@Url.Action("AddToCart", "Catalogue")')">Toevoegen aan winkelmandje</a>
                    <button @(Model.BeschikbareItems == null ? "disabled" : "") class="like btn btn-dark @(Model.BeschikbareItems == null ? "disabled" : "")" type="button"><span class="fa fa-heart"></span></button>
                </div>
            </div>
        </div>
    }

</div>